# This is a basic workflow to help you get started with Actions

name: CI Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - develop
    - feature/*
    - master 
    - bugfix/*
    - hotfix/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
      name: Run Unit Test
      runs-on: macOS-latest
      strategy:
        matrix:
          xcode: ['/Applications/Xcode_11.4.app/Contents/Developer']
      steps:
        - name: Checkout Branch
          uses: actions/checkout@v1
        - name: Install Dependencies
          run: bundle install 
#           env:
#             BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        - name: Prepare iOS Simulators
          run: |
            sudo bundle exec xcversion simulators --install="iOS 11.4 Simulator" --verbose --no-progress
            sudo bundle exec xcversion simulators --install="iOS 12.4 Simulator" --verbose --no-progress
            sudo bundle exec xcversion simulators --install="iOS 13.6 Simulator" --verbose --no-progress
            xcrun simctl list runtimes
            xcrun simctl create custom-test-device "iPhone 8" "com.apple.CoreSimulator.SimRuntime.iOS-11-4"
            xcrun simctl create custom-test-device "iPhone SE" "com.apple.CoreSimulator.SimRuntime.iOS-12-4"
            xcrun simctl create custom-test-device "iPhone X" "com.apple.CoreSimulator.SimRuntime.iOS-13-6"
            xcrun simctl create custom-test-device "iPad Air" "com.apple.CoreSimulator.SimRuntime.iOS-11-4"
            xcrun simctl create custom-test-device "iPad Air 2" "com.apple.CoreSimulator.SimRuntime.iOS-12-4"
            xcrun simctl create custom-test-device "iPad Pro (10.5-inch)" "com.apple.CoreSimulator.SimRuntime.iOS-13-6"
            xcrun simctl list devices 11.4
            xcrun simctl list devices 12.4
            xcrun simctl list devices 13.6
        - name: Build and test on iPhones
          run: bundle exec fastlane run_ci_tests devices:"${destination}" --verbose
          env:
            destination: ${{ '["platform=iOS Simulator,OS=11.4,name=iPhone 8","platform=iOS Simulator,OS=12.4,name=iPhone SE","platform=iOS Simulator,OS=13.6,name=iPhone X","iPhone 11"]' }}
        - name: Build and test on iPads
          run: bundle exec fastlane run_ci_tests devices:"${destination}" --verbose
          env:
            destination: ${{ '["platform=iOS Simulator,OS=11.4,name=iPad Air","platform=iOS Simulator,OS=12.4,name=iPad Air 2","platform=iOS Simulator,OS=13.6,name=iPad Pro (10.5-inch)","iPad Pro (12.9-inch)"]' }}
        - name: Archive Failed Tests artifacts
          if: failure()
          uses: actions/upload-artifact@v1
          with:
            name: FailureDiff
            path: fastlane/test_output
